### PR TITLE
Allow connections through SSL

### PR DESCRIPTION
**Pull request by rborer**
Using the :ssl? true parameter allow to enable SSL connections (using the default SSLSocketFactory).

PircBotX version has been bumped to 1.9 (2.0 introduce major breaking changes).

I've also added the :verbose? parameter (useful to debug non-working client), and removed all reflection warnings :-)

### CODE REVIEW

**Comment by obohrer** [comment]
Thank you ! Should be released to clojars later this week !

**Comment by rborer** [comment]
Awesome, thanks!

**Comment by rborer** [comment]
@obohrer any news of clojars release? It seems to be still not released 😢

**Comment by obohrer** [comment]
Wow this was a looong week ! It has been deployed to clojars now.
Sorry for the wait (back to CH now, let me know if you want to catch up with a drink :) )

**Pull request merged**
